"""add name to report params

Revision ID: 09e4cc607899
Revises: f634e351cb33
Create Date: 2024-02-22 00:01:59.623048

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '09e4cc607899'
down_revision = 'f634e351cb33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('reportparams', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reportparams', 'name')
    op.alter_column('report', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
