"""add report statuses

Revision ID: 3f45b80c5ef3
Revises: c701a950e445
Create Date: 2024-03-03 21:51:22.120845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f45b80c5ef3'
down_revision = 'c701a950e445'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint("report_id", "service_id", name="report_id_service_id_unique"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportstatus')
    # ### end Alembic commands ###
