"""rename type name in params

Revision ID: c701a950e445
Revises: 3e88b86c020a
Create Date: 2024-03-03 00:21:36.571210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c701a950e445'
down_revision = '3e88b86c020a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='reportparameter', column_name='params_type', new_column_name='type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='reportparameter', column_name='type', new_column_name='params_type')
    # ### end Alembic commands ###
