"""add version to params

Revision ID: d9469310a5a6
Revises: 09e4cc607899
Create Date: 2024-02-22 01:48:38.381331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9469310a5a6'
down_revision = '09e4cc607899'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reportimage', 'data',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.add_column('reportparams', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('reportparams', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reportparams', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('reportparams', 'version')
    op.alter_column('reportimage', 'data',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('report', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
